// <auto-generated />
using System;
using KolibSoftware.Api.Example;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KolibSoftware.Api.Example.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260409211749_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KolibSoftware.Api.Example.Models.DocumentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(2560)")
                        .HasAnnotation("MariaDB:VectorColumn", "VECTOR(2560)");

                    b.Property<Guid>("Rid")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("tinytext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("Rid")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("document", (string)null);
                });

            modelBuilder.Entity("KolibSoftware.Api.Infra.Models.EventModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("tinytext");

                    b.Property<Guid>("Rid")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('Pending','Success','Partial','Failure')");

                    b.HasKey("Id");

                    b.HasIndex("Rid")
                        .IsUnique();

                    b.ToTable("event", (string)null);
                });

            modelBuilder.Entity("KolibSoftware.Api.Infra.Models.TaskDependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DependencyId")
                        .HasColumnType("int");

                    b.Property<int>("DependentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DependencyId");

                    b.HasIndex("DependentId");

                    b.ToTable("task_dependency", (string)null);
                });

            modelBuilder.Entity("KolibSoftware.Api.Infra.Models.TaskModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("tinytext");

                    b.Property<Guid>("Rid")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('Pending','Success','Cancelled','Failure')");

                    b.HasKey("Id");

                    b.HasIndex("Rid")
                        .IsUnique();

                    b.ToTable("task", (string)null);
                });

            modelBuilder.Entity("KolibSoftware.Api.Infra.Models.TaskDependency", b =>
                {
                    b.HasOne("KolibSoftware.Api.Infra.Models.TaskModel", "Dependency")
                        .WithMany("Dependents")
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KolibSoftware.Api.Infra.Models.TaskModel", "Dependent")
                        .WithMany("Dependencies")
                        .HasForeignKey("DependentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependency");

                    b.Navigation("Dependent");
                });

            modelBuilder.Entity("KolibSoftware.Api.Infra.Models.TaskModel", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Dependents");
                });
#pragma warning restore 612, 618
        }
    }
}
